package ppd.com.mubler.ui.register;

public enum RegisterError {
    EMPTY_EMAIL,
    EMPTY_CONFIRM_EMAIL,
    EMPTY_PASSWORD,
    EMPTY_LASTNAME,
    EMPTY_FIRSTNAME,
    EMPTY_DATEOFBIRTH,
    WEAK_PASSWORD,
    EMAIL_ALREADY_USED,
    INVALID_EMAIL,
    UNKNOWN,
    INVALID_INPUT_DATE,
    EMAIL_CONFIRMATION_FAILED,
    PASSWORD_CONFIRMATION_FAILED
}
